"
Please, use {{gtClass:TBlHorizontalTreeFlowLayoutScrollable}} instead.
"
Trait {
	#name : #TBlHorizontalTreeFlowLayoutSmooth,
	#traits : 'TBlHorizontalTreeFlowLayoutScrollable',
	#classTraits : 'TBlHorizontalTreeFlowLayoutScrollable classTrait',
	#category : #'BlocPac-Scrollable-Tree-Flow'
}

{ #category : #testing }
TBlHorizontalTreeFlowLayoutSmooth classSide >> isDeprecated [
	"Plaase, use `TBlHorizontalTreeFlowLayoutScrollable` instead."

	^ true
]
